CXX = g++
CC = gcc
CXXFLAGS = -std=c++17 -Wall -Wextra -D_USE_MATH_DEFINES
CFLAGS = -Wall -Wextra
LDFLAGS =

SHELL = /usr/bin/bash

# GLAD include path (must come BEFORE system includes)
GLAD_INCLUDE := -Ilib/glad/include

# Always expose the GLAD headers, even when GLFW is unavailable.
CXXFLAGS += $(GLAD_INCLUDE)
CFLAGS += $(GLAD_INCLUDE)

# Expose actor facades outside the engine directory
CXXFLAGS += -Iactors
CFLAGS += -Iactors
# Ensure engine include path is available for internal headers
CXXFLAGS += -I./engine
CFLAGS += -I./engine

GLFW_CFLAGS := $(shell pkg-config --cflags glfw3 2>/dev/null)
GLFW_LIBS  := $(shell pkg-config --libs glfw3 2>/dev/null)

# Fallback if pkg-config fails (Windows toolchain support)
ifeq ($(GLFW_LIBS),)
ifeq ($(OS),Windows_NT)
GLFW_CFLAGS := -IC:/msys64/mingw64/include
GLFW_LIBS := -LC:/msys64/mingw64/lib -lglfw3
endif
endif

ifneq ($(GLFW_LIBS),)
	CXXFLAGS += $(GLFW_CFLAGS) -DUSE_GLFW
	LDLIBS += $(GLFW_LIBS)
ifneq ($(OS),Windows_NT)
	LDLIBS += -lGLU
endif
ifeq ($(OS),Windows_NT)
	LDLIBS += -lopengl32 -lglu32 -lfreeglut
endif
$(info GLFW detected: building with GLFW support)
else
$(info GLFW not found; building ASCII fallback)
endif

# FreeType detection for SVG text rasterization
FREETYPE_CFLAGS := $(shell pkg-config --cflags freetype2 2>/dev/null)
FREETYPE_LIBS := $(shell pkg-config --libs freetype2 2>/dev/null)

ifneq ($(FREETYPE_LIBS),)
	CXXFLAGS += $(FREETYPE_CFLAGS) -DUSE_FREETYPE
	LDLIBS += $(FREETYPE_LIBS)
else
ifeq ($(OS),Windows_NT)
	CXXFLAGS += -IC:/msys64/mingw64/include/freetype2 -DUSE_FREETYPE
	LDLIBS += -LC:/msys64/mingw64/lib -lfreetype
else
$(info FreeType not found; SVG text rendering will be disabled)
endif
endif

# Include graphics subsystem and GLAD loader
SRC := $(wildcard engine/*.cpp) $(wildcard actors/*.cpp) \
       $(wildcard engine/ecs/*.cpp) $(wildcard engine/physics/*.cpp) \
       $(wildcard engine/ai/*.cpp) $(wildcard engine/navigation/*.cpp) \
       $(wildcard engine/gameplay/*.cpp)
GLAD_SRC :=
GLAD_OBJ :=

# Auto-include all actor headers for registration
ACTOR_HEADERS := $(wildcard actors/*.h)
ACTOR_INCLUDES := $(foreach header,$(ACTOR_HEADERS),#include "$(header)")

# Generate Actors.h automatically
ifeq ($(OS),Windows_NT)
engine/Actors.h: $(ACTOR_HEADERS)
	generate_actors.bat
else
engine/Actors.h: $(ACTOR_HEADERS)
	python3 scripts/generate_actors_header.py
endif

ifeq ($(GLFW_LIBS),)
SRC := $(filter-out engine/PostProcessPipeline.cpp engine/TextRenderer.cpp,$(SRC))
SRC := $(filter-out engine/MainLoop.cpp engine/Viewport3D.cpp,$(SRC))
else
SRC += $(wildcard engine/graphics/*.cpp)
GLAD_SRC := lib/glad/src/glad.c
GLAD_OBJ := $(patsubst %.c,%.o,$(GLAD_SRC))
endif

OBJ := $(filter-out engine/test_sdl.o engine/main_test.o, $(patsubst %.cpp,%.o,$(SRC)))
TARGET := nova-engine

# Ensure Actors.h is up to date before compiling
engine/EngineBootstrap.o: engine/Actors.h

# Test executables generated by the "test" target.
TEST_BINS := tests/test_simulation tests/test_camera tests/test_camera_follow \
        tests/test_camera_edgecases tests/test_camera_presets \
        tests/test_ship_assembly tests/test_shield_energy \
        tests/test_feedback_systems tests/test_text_rendering \
        tests/test_ecs_v2 tests/test_physics tests/test_solar_system \
        tests/test_animation_system tests/test_entity_migration \
        tests/test_simulation_scheduler tests/test_weapon_targeting \
	tests/test_ship_battle_benchmark tests/test_ship_assembly_validation \
	tests/test_physics_behaviors tests/test_subsystem_damage_stress \
        tests/test_frame_pacing_controller tests/test_mesh_submission_standalone \
        tests/test_system_manager tests/test_system_integration \
        tests/test_ecs_transition_fuzz tests/bench_ecs_hot_paths \
        tests/test_player_actor test_actor_rendering_full

# Files and binaries that should be removed by "make clean" on every platform.
CLEAN_TARGETS := $(OBJ) $(GLAD_OBJ) $(TARGET) $(TARGET).exe $(TEST_BINS) \
        $(addsuffix .exe,$(TEST_BINS))

# Pre-quote the file list for the Windows command prompt so each path is removed
# safely, even when it contains forward slashes.
WINDOWS_CLEAN_TARGETS := $(foreach path,$(CLEAN_TARGETS),"$(subst /,\,$(path))")

all: $(TARGET)

# Compile GLAD first (C code)
ifneq ($(GLAD_OBJ),)
$(GLAD_OBJ): $(GLAD_SRC)
	$(CC) $(CFLAGS) -c $< -o $@
endif

# Link with GLAD object file
$(TARGET): $(GLAD_OBJ) $(OBJ)
	$(CXX) $(CXXFLAGS) $(LDFLAGS) -o $@ $(GLAD_OBJ) $(OBJ) $(LDLIBS)

run: $(TARGET)
ifeq ($(OS),Windows_NT)
	./$(TARGET).exe
else
	./$(TARGET)
endif

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -c $< -o $@

test: tests/test_simulation tests/test_camera tests/test_camera_follow tests/test_camera_edgecases tests/test_camera_presets tests/test_ship_assembly tests/test_shield_energy tests/test_feedback_systems tests/test_text_rendering tests/test_ecs_v2 tests/test_physics tests/test_solar_system tests/test_animation_system tests/test_weapon_targeting tests/test_ship_battle_benchmark tests/test_ship_assembly_validation tests/test_physics_behaviors tests/test_subsystem_damage_stress tests/test_frame_pacing_controller tests/test_system_manager tests/test_system_integration tests/test_player_actor tests/test_spaceship_actor

tests/test_simulation: tests/test_simulation.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_simulation.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_camera: tests/test_camera.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_camera.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_camera_follow: tests/test_camera_follow.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_camera_follow.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_camera_edgecases: tests/test_camera_edgecases.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_camera_edgecases.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_camera_presets: tests/test_camera_presets.cpp tests/gl_stub.cpp
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_camera_presets.cpp tests/gl_stub.cpp $(LDLIBS)

tests/test_ship_assembly: tests/test_ship_assembly.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_ship_assembly.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_shield_energy: tests/test_shield_energy.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_shield_energy.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_feedback_systems: tests/test_feedback_systems.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_feedback_systems.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_text_rendering: tests/test_text_rendering.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_text_rendering.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_ecs_v2: tests/test_ecs_v2.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_ecs_v2.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_ecs_transition_fuzz: tests/test_ecs_transition_fuzz.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_ecs_transition_fuzz.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_physics: tests/test_physics.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_physics.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_solar_system: tests/test_solar_system.cpp engine/SolarSystem.cpp engine/CelestialBody.cpp engine/Transform.cpp engine/ecs/EntityManager.cpp engine/ecs/ArchetypeManager.cpp engine/ecs/TransitionPlan.cpp engine/Mesh.cpp tests/gl_stub.cpp
	$(CXX) $(CXXFLAGS) -Ilib/glad/include -I./engine -o $@ tests/test_solar_system.cpp engine/SolarSystem.cpp engine/CelestialBody.cpp engine/Transform.cpp engine/ecs/EntityManager.cpp engine/ecs/ArchetypeManager.cpp engine/ecs/TransitionPlan.cpp engine/Mesh.cpp tests/gl_stub.cpp $(LDLIBS)


tests/test_animation_system: tests/test_animation_system.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_animation_system.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_weapon_targeting: tests/test_weapon_targeting.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_weapon_targeting.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_ship_battle_benchmark: tests/test_ship_battle_benchmark.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_ship_battle_benchmark.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/bench_ecs_hot_paths: tests/bench_ecs_hot_paths.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/bench_ecs_hot_paths.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_ship_assembly_validation: tests/test_ship_assembly_validation.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_ship_assembly_validation.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_physics_behaviors: tests/test_physics_behaviors.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_physics_behaviors.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_subsystem_damage_stress: tests/test_subsystem_damage_stress.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_subsystem_damage_stress.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_frame_pacing_controller: tests/test_frame_pacing_controller.cpp engine/FramePacingController.cpp
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_frame_pacing_controller.cpp engine/FramePacingController.cpp $(LDLIBS)

tests/test_primitive_mesh: tests/test_primitive_mesh.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_primitive_mesh.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

# A lightweight standalone build for the PrimitiveMesh unit test that avoids linking
# the entire engine (safer for quick headless runs during development).
tests/test_primitive_mesh_standalone:
	$(CXX) $(CXXFLAGS) -DPRIMITIVEMESH_FORCE_NO_GL -I./engine -o $@ tests/test_primitive_mesh.cpp engine/graphics/PrimitiveMesh.cpp

tests/test_mesh_submission_standalone:
	$(CXX) $(CXXFLAGS) -DPRIMITIVEMESH_FORCE_NO_GL -I./engine -o $@ tests/test_mesh_submission.cpp engine/graphics/MeshSubmission.cpp engine/graphics/PrimitiveMesh.cpp engine/Mesh.cpp

tests/test_viewport_headless: tests/test_viewport_headless.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_viewport_headless.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_system_manager: tests/test_system_manager.cpp engine/ecs/System.cpp engine/ecs/EntityManager.cpp engine/ecs/ArchetypeManager.cpp engine/ecs/TransitionPlan.cpp
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_system_manager.cpp engine/ecs/System.cpp engine/ecs/EntityManager.cpp engine/ecs/ArchetypeManager.cpp engine/ecs/TransitionPlan.cpp $(LDLIBS)

tests/test_system_integration: tests/test_system_integration.cpp engine/ecs/System.cpp engine/ecs/EntityManager.cpp engine/ecs/ArchetypeManager.cpp engine/ecs/TransitionPlan.cpp
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_system_integration.cpp engine/ecs/System.cpp engine/ecs/EntityManager.cpp engine/ecs/ArchetypeManager.cpp engine/ecs/TransitionPlan.cpp $(LDLIBS)

tests/test_player_actor: tests/test_player_actor.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ tests/test_player_actor.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

test_actor_rendering_full: test_actor_rendering_full.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ)
	$(CXX) $(CXXFLAGS) -I./engine -o $@ test_actor_rendering_full.cpp $(filter-out engine/main.o,$(OBJ)) $(GLAD_OBJ) $(LDLIBS)

tests/test_spaceship_actor: test_spaceship_actor.cpp actors/Spaceship.o engine/SimpleJson.o
	$(CXX) $(CXXFLAGS) -I./engine -o $@ test_spaceship_actor.cpp actors/Spaceship.o engine/SimpleJson.o $(LDLIBS)

ifeq ($(OS),Windows_NT)
clean:
	@cmd /C "del /F /Q $(WINDOWS_CLEAN_TARGETS) >nul 2>&1"
else
clean:
	rm -f $(CLEAN_TARGETS)
endif

.PHONY: all test clean run

